language: go

sudo: false

addons:
 apt:
   packages:
    - libpcap0.8-dev

matrix:
  include:
  - go: "1.13.x"
  - go: "1.14.x"
  - go: master
  allow_failures:
  - go: master
  fast_finish: true

env:
 - GO111MODULE=on

script:
 - go build ./...
 - go test ./...
